# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 237dc50ce33384b2cf5dcf30c32ba1a4e821a849b698fc9fc30c3816db58e19cedd44322e646f97fe3c116c6e7ba00ca8d61ff99df43fabad67b78103f250264

test:
  secret_key_base: 71e880bdd85cab10af8bcb89ab589a7485ef09151da9b504023ce0c89745cfac560ca50c21d3435355b5fe0e06017a0ac9c14aa95d07c7c1b4335f67ac96eea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
